# -*- coding: utf-8 -*-
"""comp_ling_doc_sim_jaccard.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19mNmY7YrH3KLfCTiNnsNOXulecebG_vc
"""

import spacy
import numpy as np
from typing import *
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

nlp = spacy.load("en_core_web_sm")

# define a function for lemmatization
def lemmatize_text(text: str) -> str:
  doc = nlp(text)
  lemmatized_text = " ".join([token.lemma_ for token in doc if not token.is_stop and not token.is_punct])
  return lemmatized_text

# define a function to preprocess and tokenize texts with lemmatization
def preprocess_texts(texts: List[str]) -> List[str]:
  preprocessed_texts = [lemmatize_text(text) for text in texts]
  return preprocessed_texts

# define a function to calculate TF-IDF scores and return keyword dictionary
def calculate_tfidf_keywords(texts: List[str]) -> Dict[str, List[str]]:
  tfidf_vectorizer = TfidfVectorizer()
  tfidf_matrix = tfidf_vectorizer.fit_transform(texts)

  keywords_dict = {}
  for i, text in enumerate(texts):
    tfidf_scores_i = tfidf_matrix[i]
    keyword_indices = np.argsort(tfidf_scores_i.toarray())[0][::-1]
    top_keywords = [tfidf_vectorizer.get_feature_names_out()[index] for index in keyword_indices[:5]]
    keywords_dict[str(i)] = top_keywords

  return keywords_dict

# define a function to find similar keywords using Jaccard similarity
def find_similar_keywords(keywords_dict: Dict[str, List[str]], threshold: float=0.1) -> Dict[str, List[str]]:
  similar_keywords_dict = {}

  for i in range(len(texts)):
    for j in range(i + 1, len(texts)):
      keywords_i = set(keywords_dict[str(i)])
      keywords_j = set(keywords_dict[str(j)])

      jaccard_similarity = len(keywords_i.intersection(keywords_j)) / len(keywords_i.union(keywords_j))

      if jaccard_similarity > threshold:
        if str(i) not in similar_keywords_dict:
          similar_keywords_dict[str(i)] = []
        if str(j) not in similar_keywords_dict:
          similar_keywords_dict[str(j)] = []

        similar_keywords_dict[str(i)].extend(keywords_dict[str(j)])
        similar_keywords_dict[str(j)].extend(keywords_dict[str(i)])

  return similar_keywords_dict

if __name__ == "__main__":
  texts = [
    "In the intricate landscape of global politics, leaders navigate the complexities of international relations, domestic policies, and public opinion. The decisions made by political figures reverberate across societies, shaping the future of nations. Political ideologies clash, parties debate, and citizens engage, creating a dynamic environment where the quest for power and the pursuit of the greater good often collide.",

    "In the realm of politics, the constant ebb and flow of ideas and policies shape the destiny of nations. The delicate balance between diplomacy and assertiveness defines a nation's stance on the world stage. Political debates echo in the halls of power, where leaders grapple with economic challenges, social reforms, and foreign relations. Through the democratic process, citizens hold the key to change, ensuring that their voices are heard and their rights protected.",

    "Football, the beautiful game, unites people from diverse backgrounds under the banner of passion and competition. Stadiums echo with the cheers of fans, celebrating the artistry of players and the thrill of goals. From local leagues to international tournaments, the spirit of sportsmanship transcends borders, fostering camaraderie among nations. Every match is a story, written on the pitch with skill and determination, capturing the hearts of millions worldwide.",

    "In the world of football, every match is a saga of determination and teamwork. Players, guided by coaches, strive for excellence on the field, showcasing their talent and dedication. From grassroots development to elite competitions, football fosters discipline, resilience, and the pursuit of dreams. Behind every goal and every victory lies hours of training, strategic planning, and unwavering passion, making football not just a sport but a way of life for enthusiasts around the globe.",

    "Football, a universal language, bridges cultural gaps and fosters a sense of belonging among fans. The anticipation before a match, the thrill of a perfectly executed play, and the heart-stopping moments of penalty shootouts - these experiences bind communities together. Beyond the scorelines, football sparks conversations, forges friendships, and instills values of teamwork and fair play. As players dribble and score, they inspire generations, leaving an indelible mark on the world's most popular sport.",

    "Legislation forms the backbone of every just society, providing the framework for governance, justice, and individual rights. Lawmakers meticulously craft statutes and regulations, addressing societal issues and safeguarding the well-being of citizens. The legislative process, often marked by debates and compromises, is a testament to democracy in action, ensuring that laws reflect the collective conscience and aspirations of the people.",

    "In the corridors of power, legislation takes shape through rigorous debate, research, and public discourse. Laws are the embodiment of a society's values, addressing contemporary challenges and envisioning a better future. Legal frameworks evolve, adapting to the changing needs of communities and embracing principles of equality and justice. Behind every statute lies a commitment to upholding the rule of law, empowering citizens, and promoting a harmonious coexistence.",

    "Climate change, a defining challenge of our era, compels nations to confront environmental threats and embrace sustainable practices. Rising temperatures, extreme weather events, and environmental degradation necessitate global cooperation to mitigate the impact on ecosystems and human societies. Through innovative technologies, conservation efforts, and policy reforms, humanity strives to preserve the planet for future generations, acknowledging the urgent need for collective action against climate change.",

    "Australia, a vast continent adorned with diverse landscapes, captivates the world with its natural wonders and vibrant culture. From the iconic Sydney Opera House to the awe-inspiring Great Barrier Reef, the country's landmarks inspire awe and admiration. Aboriginal heritage weaves a rich tapestry of traditions, connecting the past with the present. Australia's unique wildlife, including kangaroos and koalas, symbolize the country's ecological uniqueness, making it a destination of choice for travelers seeking both adventure and serenity."
]

  preprocessed_texts = preprocess_texts(texts)
  keywords_dict = calculate_tfidf_keywords(preprocessed_texts)

  jaccard_similarity_threshold = 0.1
  similar_keywords_dict = find_similar_keywords(keywords_dict, jaccard_similarity_threshold)
  print("Keywords Dictionary")
  print(keywords_dict)
  print("\nSimilar Keywords Dictionary: ")
  print(similar_keywords_dict)

